/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tripleo.impohrt.cl;


public class SWIGTYPE_p_f_p_struct_clThreadData__void {
  private final long swigCPtr;

  protected SWIGTYPE_p_f_p_struct_clThreadData__void(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_struct_clThreadData__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_struct_clThreadData__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

