/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#if defined(__GNUC__)
    typedef long long __int64; /*For gcc on Windows */
#endif
#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "cl.h"

extern void clResetError();
extern void clPrintError();
extern int clGetErrorCode();
extern void clGetErrorMessage(char *);
extern void clSetErrorCallback(void (*)(char *,int));
extern int clBegin();
extern SOCKET clConnect(char *,char *,char *);
extern SOCKET clConnectPort(char *,unsigned short,char *);
extern int clAsyncSocket(SOCKET);
extern int clSyncSocket(SOCKET);
extern int clBytesAvailable(SOCKET);
extern SOCKET clTcpSyncSocket();
extern SOCKET clUdpSyncSocket();
extern SOCKET clTcpAsyncSocket();
extern SOCKET clUdpAsyncSocket();
extern SOCKET clBroadcastSocket();
extern unsigned short clGetPortByService(char *,char *);
extern int clDisconnect(SOCKET);
extern int clClose(SOCKET);
extern int clEnd();
extern void clSetSRDelay(int);
extern int clGetSRDelay();
extern int clGetRemoteName(SOCKET,char *,char *);
extern int clSend(SOCKET,char *,int);
extern int clRecv(SOCKET,char *,int);
extern int clAsyncRecv(SOCKET,char *,int,int);
extern int clAsyncSend(SOCKET,char *,int,int);
extern int clSendTo(SOCKET,char *,int,char *,unsigned short);
extern int clRecvFrom(SOCKET,char *,int,char *,int,unsigned short);
extern int clAsyncRecvFrom(SOCKET,char *,int,char *,int,unsigned short,int);
extern int clAsyncSendTo(SOCKET,char *,int,char *,unsigned short,int);
extern int clBroadcast(SOCKET,char *,int,unsigned short);
extern int clSendAll(SOCKET,char *,int);
extern int clRecvAll(SOCKET,char *,int);
extern SOCKET clEstablish(unsigned short,int);
extern SOCKET clWaitNewConnection(SOCKET);
extern int clServerByPort(unsigned short,int,void (*)(struct clThreadData *),struct clThreadData *);
extern int clKillParent(int);
extern int clSelect(int [],int [],int,int,int);

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1ERRMSG_1SIZE(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 256;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1HOSTNAME_1SIZE(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 256;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) -1;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1NOERROR(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 0;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1UNKNOWN_1HOST(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 1;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1INVALID_1SOCKET(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 2;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1CONNECTION_1UNAVAIL(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 3;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1UNKNOWN_1SERVICE(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 4;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1INIT_1FAILED(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 5;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1LIBCLOSE_1FAILED(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 6;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1CLOSE_1SOCKET(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 7;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1MEMORY_1ALLOC(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 8;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1NULL_1POINTER(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 9;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1SOCKET_1ATTR(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 23;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1SOCKET_1BIND(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 24;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1TIMEOUT(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 25;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1SOCKET_1BROADCAST(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 26;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1SOCKET_1CREATE(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 27;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1ACCEPT(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 28;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERRX_1FORK(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 29;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERRW_1THREAD(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 30;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_get_1CL_1ERR_1SELECT(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int) 31;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_set_1clThreadData_1sock(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    struct clThreadData *arg1 = (struct clThreadData *) 0 ;
    SOCKET arg2 ;
    SOCKET *argp2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct clThreadData **)&jarg1; 
    argp2 = *(SOCKET **)&jarg2; 
    if (!argp2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return ;
    }
    arg2 = *argp2; 
    if (arg1) (arg1)->sock = arg2;
    
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_get_1clThreadData_1sock(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct clThreadData *arg1 = (struct clThreadData *) 0 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct clThreadData **)&jarg1; 
    result =  ((arg1)->sock);
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_set_1clThreadData_1data(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    struct clThreadData *arg1 = (struct clThreadData *) 0 ;
    void *arg2 = (void *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct clThreadData **)&jarg1; 
    arg2 = *(void **)&jarg2; 
    if (arg1) (arg1)->data = arg2;
    
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_get_1clThreadData_1data(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct clThreadData *arg1 = (struct clThreadData *) 0 ;
    void *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct clThreadData **)&jarg1; 
    result = (void *) ((arg1)->data);
    
    *(void **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_new_1clThreadData(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    struct clThreadData *result;
    
    (void)jenv;
    (void)jcls;
    result = (struct clThreadData *)(struct clThreadData *) calloc(1, sizeof(struct clThreadData));
    
    *(struct clThreadData **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_delete_1clThreadData(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct clThreadData *arg1 = (struct clThreadData *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct clThreadData **)&jarg1; 
    free((char *) arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_clResetError(JNIEnv *jenv, jclass jcls) {
    (void)jenv;
    (void)jcls;
    clResetError();
    
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_clPrintError(JNIEnv *jenv, jclass jcls) {
    (void)jenv;
    (void)jcls;
    clPrintError();
    
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clGetErrorCode(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int)clGetErrorCode();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_clGetErrorMessage(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    char *arg1 ;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
            if (!arg1) return ;
        }
    }
    clGetErrorMessage(arg1);
    
    {
        if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1); 
    }
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_clSetErrorCallback(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    void (*arg1)(char *,int) = (void (*)(char *,int)) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(void (**)(char *,int))&jarg1; 
    clSetErrorCallback(arg1);
    
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_get_1errCallback(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    void (*result)(char *,int);
    
    (void)jenv;
    (void)jcls;
    result = (void (*)(char *,int)) NULL;
    
    *(void (**)(char *,int))&jresult = result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clBegin(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int)clBegin();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clConnect(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2, jstring jarg3) {
    jlong jresult = 0 ;
    char *arg1 ;
    char *arg2 ;
    char *arg3 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
            if (!arg1) return 0;
        }
    }
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    {
        arg3 = 0;
        if (jarg3) {
            arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
            if (!arg3) return 0;
        }
    }
    result = clConnect(arg1,arg2,arg3);
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    {
        if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1); 
    }
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    {
        if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, arg3); 
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clConnectPort(JNIEnv *jenv, jclass jcls, jstring jarg1, jint jarg2, jstring jarg3) {
    jlong jresult = 0 ;
    char *arg1 ;
    unsigned short arg2 ;
    char *arg3 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
            if (!arg1) return 0;
        }
    }
    arg2 = (unsigned short)jarg2; 
    {
        arg3 = 0;
        if (jarg3) {
            arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
            if (!arg3) return 0;
        }
    }
    result = clConnectPort(arg1,arg2,arg3);
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    {
        if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1); 
    }
    {
        if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, arg3); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clAsyncSocket(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    result = (int)clAsyncSocket(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clSyncSocket(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    result = (int)clSyncSocket(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clBytesAvailable(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    result = (int)clBytesAvailable(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clTcpSyncSocket(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    result = clTcpSyncSocket();
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clUdpSyncSocket(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    result = clUdpSyncSocket();
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clTcpAsyncSocket(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    result = clTcpAsyncSocket();
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clUdpAsyncSocket(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    result = clUdpAsyncSocket();
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clBroadcastSocket(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    result = clBroadcastSocket();
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clGetPortByService(JNIEnv *jenv, jclass jcls, jstring jarg1, jstring jarg2) {
    jint jresult = 0 ;
    char *arg1 ;
    char *arg2 ;
    unsigned short result;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
            if (!arg1) return 0;
        }
    }
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    result = (unsigned short)clGetPortByService(arg1,arg2);
    
    jresult = (jint)result; 
    {
        if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1); 
    }
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clDisconnect(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    result = (int)clDisconnect(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clClose(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    result = (int)clClose(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clEnd(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int)clEnd();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_impohrt_cl_clJNI_clSetSRDelay(JNIEnv *jenv, jclass jcls, jint jarg1) {
    int arg1 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1; 
    clSetSRDelay(arg1);
    
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clGetSRDelay(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int)clGetSRDelay();
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clGetRemoteName(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jstring jarg3) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    char *arg3 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    {
        arg3 = 0;
        if (jarg3) {
            arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
            if (!arg3) return 0;
        }
    }
    result = (int)clGetRemoteName(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    {
        if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, arg3); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clSend(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    result = (int)clSend(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clRecv(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    result = (int)clRecv(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clAsyncRecv(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jint jarg4) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    int arg4 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    arg4 = (int)jarg4; 
    result = (int)clAsyncRecv(arg1,arg2,arg3,arg4);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clAsyncSend(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jint jarg4) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    int arg4 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    arg4 = (int)jarg4; 
    result = (int)clAsyncSend(arg1,arg2,arg3,arg4);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clSendTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jstring jarg4, jint jarg5) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    unsigned short arg5 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    {
        arg4 = 0;
        if (jarg4) {
            arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
            if (!arg4) return 0;
        }
    }
    arg5 = (unsigned short)jarg5; 
    result = (int)clSendTo(arg1,arg2,arg3,arg4,arg5);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    {
        if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, arg4); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clRecvFrom(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jstring jarg4, jint jarg5, jint jarg6) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    unsigned short arg6 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    {
        arg4 = 0;
        if (jarg4) {
            arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
            if (!arg4) return 0;
        }
    }
    arg5 = (int)jarg5; 
    arg6 = (unsigned short)jarg6; 
    result = (int)clRecvFrom(arg1,arg2,arg3,arg4,arg5,arg6);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    {
        if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, arg4); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clAsyncRecvFrom(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jstring jarg4, jint jarg5, jint jarg6, jint jarg7) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    int arg5 ;
    unsigned short arg6 ;
    int arg7 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    {
        arg4 = 0;
        if (jarg4) {
            arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
            if (!arg4) return 0;
        }
    }
    arg5 = (int)jarg5; 
    arg6 = (unsigned short)jarg6; 
    arg7 = (int)jarg7; 
    result = (int)clAsyncRecvFrom(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    {
        if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, arg4); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clAsyncSendTo(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jstring jarg4, jint jarg5, jint jarg6) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    char *arg4 ;
    unsigned short arg5 ;
    int arg6 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    {
        arg4 = 0;
        if (jarg4) {
            arg4 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg4, 0);
            if (!arg4) return 0;
        }
    }
    arg5 = (unsigned short)jarg5; 
    arg6 = (int)jarg6; 
    result = (int)clAsyncSendTo(arg1,arg2,arg3,arg4,arg5,arg6);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    {
        if (arg4) (*jenv)->ReleaseStringUTFChars(jenv, jarg4, arg4); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clBroadcast(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3, jint jarg4) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    unsigned short arg4 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    arg4 = (unsigned short)jarg4; 
    result = (int)clBroadcast(arg1,arg2,arg3,arg4);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clSendAll(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    result = (int)clSendAll(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clRecvAll(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
    jint jresult = 0 ;
    SOCKET arg1 ;
    char *arg2 ;
    int arg3 ;
    int result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    result = (int)clRecvAll(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clEstablish(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
    jlong jresult = 0 ;
    unsigned short arg1 ;
    int arg2 ;
    SOCKET result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (unsigned short)jarg1; 
    arg2 = (int)jarg2; 
    result = clEstablish(arg1,arg2);
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_impohrt_cl_clJNI_clWaitNewConnection(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    SOCKET arg1 ;
    SOCKET result;
    SOCKET *argp1 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(SOCKET **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null SOCKET");
        return 0;
    }
    arg1 = *argp1; 
    result = clWaitNewConnection(arg1);
    
    {
        SOCKET * resultptr = (SOCKET *) malloc(sizeof(SOCKET));
        memmove(resultptr, &result, sizeof(SOCKET));
        *(SOCKET **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clServerByPort(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2, jlong jarg3, jlong jarg4) {
    jint jresult = 0 ;
    unsigned short arg1 ;
    int arg2 ;
    void (*arg3)(struct clThreadData *) = (void (*)(struct clThreadData *)) 0 ;
    struct clThreadData *arg4 = (struct clThreadData *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (unsigned short)jarg1; 
    arg2 = (int)jarg2; 
    arg3 = *(void (**)(struct clThreadData *))&jarg3; 
    arg4 = *(struct clThreadData **)&jarg4; 
    result = (int)clServerByPort(arg1,arg2,arg3,arg4);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clKillParent(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jint jresult = 0 ;
    int arg1 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1; 
    result = (int)clKillParent(arg1);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_impohrt_cl_clJNI_clSelect(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3, jint jarg4, jint jarg5) {
    jint jresult = 0 ;
    int *arg1 ;
    int *arg2 ;
    int arg3 ;
    int arg4 ;
    int arg5 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(int **)&jarg1; 
    arg2 = *(int **)&jarg2; 
    arg3 = (int)jarg3; 
    arg4 = (int)jarg4; 
    arg5 = (int)jarg5; 
    result = (int)clSelect(arg1,arg2,arg3,arg4,arg5);
    
    jresult = (jint)result; 
    return jresult;
}


#ifdef __cplusplus
}
#endif

