/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#if defined(__GNUC__)
    typedef long long __int64; /*For gcc on Windows */
#endif
#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


typedef int intArray;

intArray *new_intArray(int nelements){
  return (int *) calloc(nelements,sizeof(int));
}
void delete_intArray(intArray *self){
  free(self);
}
int intArray_getitem(intArray *self,int index){
  return self[index];
}
void intArray_setitem(intArray *self,int index,int value){
  self[index] = value;
}
int *intArray_cast(intArray *self){
  return self;
}
intArray *intArray_frompointer(int *t){
  return (intArray *) t;
}

typedef double doubleArray;

doubleArray *new_doubleArray(int nelements){
  return (double *) calloc(nelements,sizeof(double));
}
void delete_doubleArray(doubleArray *self){
  free(self);
}
double doubleArray_getitem(doubleArray *self,int index){
  return self[index];
}
void doubleArray_setitem(doubleArray *self,int index,double value){
  self[index] = value;
}
double *doubleArray_cast(doubleArray *self){
  return self;
}
doubleArray *doubleArray_frompointer(double *t){
  return (doubleArray *) t;
}

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_new_1intArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jlong jresult = 0 ;
    int arg1 ;
    intArray *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1; 
    result = (intArray *)new_intArray(arg1);
    
    *(intArray **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_delete_1intArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    intArray *arg1 = (intArray *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(intArray **)&jarg1; 
    delete_intArray(arg1);
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_intArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    intArray *arg1 = (intArray *) 0 ;
    int arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(intArray **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (int)intArray_getitem(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_intArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    intArray *arg1 = (intArray *) 0 ;
    int arg2 ;
    int arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(intArray **)&jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (int)jarg3; 
    intArray_setitem(arg1,arg2,arg3);
    
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_intArray_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    intArray *arg1 = (intArray *) 0 ;
    int *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(intArray **)&jarg1; 
    result = (int *)intArray_cast(arg1);
    
    *(int **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_intArray_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    int *arg1 = (int *) 0 ;
    intArray *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(int **)&jarg1; 
    result = (intArray *)intArray_frompointer(arg1);
    
    *(intArray **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_new_1doubleArray(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jlong jresult = 0 ;
    int arg1 ;
    doubleArray *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1; 
    result = (doubleArray *)new_doubleArray(arg1);
    
    *(doubleArray **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_delete_1doubleArray(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    doubleArray *arg1 = (doubleArray *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(doubleArray **)&jarg1; 
    delete_doubleArray(arg1);
    
}


JNIEXPORT jdouble JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_doubleArray_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jdouble jresult = 0 ;
    doubleArray *arg1 = (doubleArray *) 0 ;
    int arg2 ;
    double result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(doubleArray **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (double)doubleArray_getitem(arg1,arg2);
    
    jresult = (jdouble)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_doubleArray_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jdouble jarg3) {
    doubleArray *arg1 = (doubleArray *) 0 ;
    int arg2 ;
    double arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(doubleArray **)&jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (double)jarg3; 
    doubleArray_setitem(arg1,arg2,arg3);
    
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_doubleArray_1cast(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    doubleArray *arg1 = (doubleArray *) 0 ;
    double *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(doubleArray **)&jarg1; 
    result = (double *)doubleArray_cast(arg1);
    
    *(double **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_extras_extraJNI_doubleArray_1frompointer(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    double *arg1 = (double *) 0 ;
    doubleArray *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(double **)&jarg1; 
    result = (doubleArray *)doubleArray_frompointer(arg1);
    
    *(doubleArray **)&jresult = result; 
    return jresult;
}


#ifdef __cplusplus
}
#endif

