/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.21
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#if defined(__GNUC__)
    typedef long long __int64; /*For gcc on Windows */
#endif
#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" } };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "tuple.h"

#include <time.h>
#include <math.h>
#include <sys/time.h>


struct timeval *
new_timeval() {
	struct timeval *s=(struct timeval *)MALLOC(sizeof(struct timeval));
	return(s);
}
void delete_timeval(struct timeval *t) {
	if(t) FREE(t);
}

extern int gettimeofday(struct timeval *,__timezone_ptr_t);


double GET_TIMEVAL_DIFF(struct timeval before, struct timeval after) {
	return ((after.tv_sec - before.tv_sec) +
	1.0e-6 * (after.tv_usec - before.tv_usec));
}


typedef union {
		int i;
		double d;
		//~ struct          {
			//~ char *ptr;
			//~ int len;
		//~ }		s;
	} element_data;



typedef int SOCKET_T;

extern int i_am_server;
extern char logbuf[8192];
extern int logptr;
extern int get_server_portnumber(struct context *);
extern void print_element(struct element *);
extern void print_tuple(struct tuple *);
extern void destroy_tuple(struct tuple *);
extern int tuples_match(struct tuple *,struct tuple *);
extern unsigned int random_int(void);
extern int send_chunk(struct context *,char *,int);
extern int send_tuple(struct context *,struct tuple *);
extern int recv_chunk(struct context *,char *,int);
extern struct tuple *recv_tuple(struct context *);
extern int put_tuple(struct tuple *,struct context *);
extern struct tuple *get_tuple(struct tuple *,struct context *);
extern struct tuple *read_tuple(struct tuple *,struct context *);
extern struct tuple *get_nb_tuple(struct tuple *,struct context *);
extern struct tuple *read_nb_tuple(struct tuple *,struct context *);
extern struct tuple_list *dump_tuple_space(struct tuple_list *,struct context *);
extern int count_tuple_space(struct tuple_list *,struct context *,int *);
extern int tuple_server_log(FILE *,struct context *);
extern int tuple_int_field(struct tuple *,int);
extern double tuple_double_field(struct tuple *,int);
extern char *tuple_string_field(struct tuple *,int *,int);
extern struct tuple *create_tuple(int const);
extern void tuple_set_int(struct tuple *,int const,int);
extern void tuple_set_double(struct tuple *,int const,double);
extern void tuple_set_str(struct tuple *,int const,char *,int);
extern void tuple_set_buf(struct tuple *,int const,void *,size_t);
extern int tuple_get_int(struct tuple *,int const);
extern double tuple_get_double(struct tuple *,int const);
extern char *tuple_get_str(struct tuple *,int const);
extern void tuple_set_nil(struct tuple *,int const);

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_new_1timeval(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    struct timeval *result;
    
    (void)jenv;
    (void)jcls;
    result = (struct timeval *)new_timeval();
    
    *(struct timeval **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_delete_1timeval(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct timeval *arg1 = (struct timeval *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct timeval **)&jarg1; 
    delete_timeval(arg1);
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_gettimeofday(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jint jresult = 0 ;
    struct timeval *arg1 = (struct timeval *) 0 ;
    __timezone_ptr_t arg2 ;
    int result;
    __timezone_ptr_t *argp2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct timeval **)&jarg1; 
    argp2 = *(__timezone_ptr_t **)&jarg2; 
    if (!argp2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null __timezone_ptr_t");
        return 0;
    }
    arg2 = *argp2; 
    result = (int)gettimeofday(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jdouble JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_GET_1TIMEVAL_1DIFF(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jdouble jresult = 0 ;
    struct timeval arg1 ;
    struct timeval arg2 ;
    double result;
    struct timeval *argp1 ;
    struct timeval *argp2 ;
    
    (void)jenv;
    (void)jcls;
    argp1 = *(struct timeval **)&jarg1; 
    if (!argp1) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null struct timeval");
        return 0;
    }
    arg1 = *argp1; 
    argp2 = *(struct timeval **)&jarg2; 
    if (!argp2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null struct timeval");
        return 0;
    }
    arg2 = *argp2; 
    result = (double)GET_TIMEVAL_DIFF(arg1,arg2);
    
    jresult = (jdouble)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1element_1tag(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    struct element *arg1 = (struct element *) 0 ;
    int arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct element **)&jarg1; 
    arg2 = (int)jarg2; 
    if (arg1) (arg1)->tag = arg2;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1element_1tag(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    struct element *arg1 = (struct element *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct element **)&jarg1; 
    result = (int) ((arg1)->tag);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1element_1data(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct element *arg1 = (struct element *) 0 ;
    element_data *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct element **)&jarg1; 
    result = (element_data *)& ((arg1)->data);
    
    *(element_data **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_new_1element(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    struct element *result;
    
    (void)jenv;
    (void)jcls;
    result = (struct element *)(struct element *) calloc(1, sizeof(struct element));
    
    *(struct element **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_delete_1element(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct element *arg1 = (struct element *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct element **)&jarg1; 
    free((char *) arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1element_1data_1i(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    element_data *arg1 = (element_data *) 0 ;
    int arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(element_data **)&jarg1; 
    arg2 = (int)jarg2; 
    if (arg1) (arg1)->i = arg2;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1element_1data_1i(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    element_data *arg1 = (element_data *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(element_data **)&jarg1; 
    result = (int) ((arg1)->i);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1element_1data_1d(JNIEnv *jenv, jclass jcls, jlong jarg1, jdouble jarg2) {
    element_data *arg1 = (element_data *) 0 ;
    double arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(element_data **)&jarg1; 
    arg2 = (double)jarg2; 
    if (arg1) (arg1)->d = arg2;
    
}


JNIEXPORT jdouble JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1element_1data_1d(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jdouble jresult = 0 ;
    element_data *arg1 = (element_data *) 0 ;
    double result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(element_data **)&jarg1; 
    result = (double) ((arg1)->d);
    
    jresult = (jdouble)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_new_1element_1data(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    element_data *result;
    
    (void)jenv;
    (void)jcls;
    result = (element_data *)(element_data *) calloc(1, sizeof(element_data));
    
    *(element_data **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_delete_1element_1data(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    element_data *arg1 = (element_data *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(element_data **)&jarg1; 
    free((char *) arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1tuple_1num_1elts(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    if (arg1) (arg1)->num_elts = arg2;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1tuple_1num_1elts(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    result = (int) ((arg1)->num_elts);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1tuple_1string_1length(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    if (arg1) (arg1)->string_length = arg2;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1tuple_1string_1length(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    result = (int) ((arg1)->string_length);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1tuple_1elements(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct element *arg2 = (struct element *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(struct element **)&jarg2; 
    if (arg1) (arg1)->elements = arg2;
    
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1tuple_1elements(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct element *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    result = (struct element *) ((arg1)->elements);
    
    *(struct element **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1tuple_1string_1space(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    char *arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return ;
        }
    }
    {
        if (arg1->string_space) free((char*)arg1->string_space);
        if (arg2) {
            arg1->string_space = (char *) malloc(strlen(arg2)+1);
            strcpy((char*)arg1->string_space,arg2);
        } else {
            arg1->string_space = 0;
        }
    }
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
}


JNIEXPORT jstring JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1tuple_1string_1space(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jstring jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    result = (char *) ((arg1)->string_space);
    
    {
        if(result) jresult = (*jenv)->NewStringUTF(jenv, result); 
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_new_1tuple(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    result = (struct tuple *)(struct tuple *) calloc(1, sizeof(struct tuple));
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_delete_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    free((char *) arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1tuple_1list_1next(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    struct tuple_list *arg1 = (struct tuple_list *) 0 ;
    struct tuple_list *arg2 = (struct tuple_list *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple_list **)&jarg1; 
    arg2 = *(struct tuple_list **)&jarg2; 
    if (arg1) (arg1)->next = arg2;
    
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1tuple_1list_1next(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct tuple_list *arg1 = (struct tuple_list *) 0 ;
    struct tuple_list *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple_list **)&jarg1; 
    result = (struct tuple_list *) ((arg1)->next);
    
    *(struct tuple_list **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1tuple_1list_1tup(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    struct tuple_list *arg1 = (struct tuple_list *) 0 ;
    struct tuple *arg2 = (struct tuple *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple_list **)&jarg1; 
    arg2 = *(struct tuple **)&jarg2; 
    if (arg1) (arg1)->tup = arg2;
    
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1tuple_1list_1tup(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct tuple_list *arg1 = (struct tuple_list *) 0 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple_list **)&jarg1; 
    result = (struct tuple *) ((arg1)->tup);
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_new_1tuple_1list(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    struct tuple_list *result;
    
    (void)jenv;
    (void)jcls;
    result = (struct tuple_list *)(struct tuple_list *) calloc(1, sizeof(struct tuple_list));
    
    *(struct tuple_list **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_delete_1tuple_1list(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct tuple_list *arg1 = (struct tuple_list *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple_list **)&jarg1; 
    free((char *) arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1context_1servername(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2) {
    struct context *arg1 = (struct context *) 0 ;
    char *arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return ;
        }
    }
    {
        if (arg2) strncpy(arg1->servername,arg2,100);
        else arg1->servername[0] = 0;
    }
    
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
}


JNIEXPORT jstring JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1context_1servername(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jstring jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    result = (char *)(char *) ((arg1)->servername);
    
    {
        if(result) jresult = (*jenv)->NewStringUTF(jenv, result); 
    }
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1context_1portnumber(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    struct context *arg1 = (struct context *) 0 ;
    int arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    arg2 = (int)jarg2; 
    if (arg1) (arg1)->portnumber = arg2;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1context_1portnumber(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    result = (int) ((arg1)->portnumber);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1context_1sock(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    struct context *arg1 = (struct context *) 0 ;
    SOCKET_T arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    arg2 = (SOCKET_T)jarg2; 
    if (arg1) (arg1)->sock = arg2;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1context_1sock(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    SOCKET_T result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    result = (SOCKET_T) ((arg1)->sock);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1context_1thr(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    struct context *arg1 = (struct context *) 0 ;
    pthread_t arg2 ;
    pthread_t *argp2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    argp2 = *(pthread_t **)&jarg2; 
    if (!argp2) {
        SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null pthread_t");
        return ;
    }
    arg2 = *argp2; 
    if (arg1) (arg1)->thr = arg2;
    
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1context_1thr(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    pthread_t result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    result =  ((arg1)->thr);
    
    {
        pthread_t * resultptr = (pthread_t *) malloc(sizeof(pthread_t));
        memmove(resultptr, &result, sizeof(pthread_t));
        *(pthread_t **)&jresult = resultptr;
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_new_1context(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    struct context *result;
    
    (void)jenv;
    (void)jcls;
    result = (struct context *)(struct context *) calloc(1, sizeof(struct context));
    
    *(struct context **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_delete_1context(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct context *arg1 = (struct context *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    free((char *) arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1i_1am_1server(JNIEnv *jenv, jclass jcls, jint jarg1) {
    int arg1 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1; 
    i_am_server = arg1;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1i_1am_1server(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int)i_am_server;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1logbuf(JNIEnv *jenv, jclass jcls, jstring jarg1) {
    char *arg1 ;
    
    (void)jenv;
    (void)jcls;
    {
        arg1 = 0;
        if (jarg1) {
            arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
            if (!arg1) return ;
        }
    }
    {
        if (arg1) strncpy(logbuf,arg1,8192);
        else logbuf[0] = 0;
    }
    
    {
        if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, arg1); 
    }
}


JNIEXPORT jstring JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1logbuf(JNIEnv *jenv, jclass jcls) {
    jstring jresult = 0 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    result = (char *)(char *)logbuf;
    
    {
        if(result) jresult = (*jenv)->NewStringUTF(jenv, result); 
    }
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_set_1logptr(JNIEnv *jenv, jclass jcls, jint jarg1) {
    int arg1 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1; 
    logptr = arg1;
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1logptr(JNIEnv *jenv, jclass jcls) {
    jint jresult = 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    result = (int)logptr;
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1server_1portnumber(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jint jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    {
        // TODO: change to typemap
        result = (int)get_server_portnumber(arg1);
        
        if (!result) {
            jclass clazz = (*jenv)->FindClass(jenv, "java/lang/Exception");
            (*jenv)->ThrowNew(jenv, clazz, "failure in linuxtuples");
            return 0;
        }
    }
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_print_1element(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct element *arg1 = (struct element *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct element **)&jarg1; 
    print_element(arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_print_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    print_tuple(arg1);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_destroy_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    destroy_tuple(arg1);
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuples_1match(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jint jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct tuple *arg2 = (struct tuple *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(struct tuple **)&jarg2; 
    result = (int)tuples_match(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_random_1int(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    unsigned int result;
    
    (void)jenv;
    (void)jcls;
    result = (unsigned int)random_int();
    
    jresult = (jlong)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_send_1chunk(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
    jint jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    char *arg2 ;
    int arg3 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    result = (int)send_chunk(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_send_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jint jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    struct tuple *arg2 = (struct tuple *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    arg2 = *(struct tuple **)&jarg2; 
    result = (int)send_tuple(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_recv_1chunk(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jint jarg3) {
    jint jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    char *arg2 ;
    int arg3 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    {
        arg2 = 0;
        if (jarg2) {
            arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
            if (!arg2) return 0;
        }
    }
    arg3 = (int)jarg3; 
    result = (int)recv_chunk(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    {
        if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, arg2); 
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_recv_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    jlong jresult = 0 ;
    struct context *arg1 = (struct context *) 0 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct context **)&jarg1; 
    result = (struct tuple *)recv_tuple(arg1);
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_put_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jint jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    result = (int)put_tuple(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jlong jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    result = (struct tuple *)get_tuple(arg1,arg2);
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_read_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jlong jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    result = (struct tuple *)read_tuple(arg1,arg2);
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_get_1nb_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jlong jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    result = (struct tuple *)get_nb_tuple(arg1,arg2);
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_read_1nb_1tuple(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jlong jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    result = (struct tuple *)read_nb_tuple(arg1,arg2);
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_dump_1tuple_1space(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jlong jresult = 0 ;
    struct tuple_list *arg1 = (struct tuple_list *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    struct tuple_list *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple_list **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    result = (struct tuple_list *)dump_tuple_space(arg1,arg2);
    
    *(struct tuple_list **)&jresult = result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_count_1tuple_1space(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
    jint jresult = 0 ;
    struct tuple_list *arg1 = (struct tuple_list *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    int *arg3 = (int *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple_list **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    arg3 = *(int **)&jarg3; 
    result = (int)count_tuple_space(arg1,arg2,arg3);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1server_1log(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
    jint jresult = 0 ;
    FILE *arg1 = (FILE *) 0 ;
    struct context *arg2 = (struct context *) 0 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(FILE **)&jarg1; 
    arg2 = *(struct context **)&jarg2; 
    result = (int)tuple_server_log(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1int_1field(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (int)tuple_int_field(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jdouble JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1double_1field(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jdouble jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    double result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (double)tuple_double_field(arg1,arg2);
    
    jresult = (jdouble)result; 
    return jresult;
}


JNIEXPORT jstring JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1string_1field(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jint jarg3) {
    jstring jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int *arg2 = (int *) 0 ;
    int arg3 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = *(int **)&jarg2; 
    arg3 = (int)jarg3; 
    result = (char *)tuple_string_field(arg1,arg2,arg3);
    
    {
        if(result) jresult = (*jenv)->NewStringUTF(jenv, result); 
    }
    return jresult;
}


JNIEXPORT jlong JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_create_1tuple(JNIEnv *jenv, jclass jcls, jint jarg1) {
    jlong jresult = 0 ;
    int arg1 ;
    struct tuple *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1; 
    result = (struct tuple *)create_tuple(arg1);
    
    *(struct tuple **)&jresult = result; 
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1set_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jint jarg3) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    int arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (int)jarg3; 
    tuple_set_int(arg1,arg2,arg3);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1set_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jdouble jarg3) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    double arg3 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    arg3 = (double)jarg3; 
    tuple_set_double(arg1,arg2,arg3);
    
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1set_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jstring jarg3, jint jarg4) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    char *arg3 ;
    int arg4 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    {
        arg3 = 0;
        if (jarg3) {
            arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
            if (!arg3) return ;
        }
    }
    arg4 = (int)jarg4; 
    tuple_set_str(arg1,arg2,arg3,arg4);
    
    {
        if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, arg3); 
    }
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1set_1buf(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jint jarg4) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    void *arg3 = (void *) 0 ;
    size_t arg4 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    arg3 = *(void **)&jarg3; 
    arg4 = (size_t)jarg4; 
    tuple_set_buf(arg1,arg2,arg3,arg4);
    
}


JNIEXPORT jint JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1get_1int(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jint jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    int result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (int)tuple_get_int(arg1,arg2);
    
    jresult = (jint)result; 
    return jresult;
}


JNIEXPORT jdouble JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1get_1double(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jdouble jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    double result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (double)tuple_get_double(arg1,arg2);
    
    jresult = (jdouble)result; 
    return jresult;
}


JNIEXPORT jstring JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1get_1str(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    jstring jresult = 0 ;
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    char *result;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    result = (char *)tuple_get_str(arg1,arg2);
    
    {
        if(result) jresult = (*jenv)->NewStringUTF(jenv, result); 
    }
    return jresult;
}


JNIEXPORT void JNICALL Java_tripleo_linuxtuples_gen_tuplesJNI_tuple_1set_1nil(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
    struct tuple *arg1 = (struct tuple *) 0 ;
    int arg2 ;
    
    (void)jenv;
    (void)jcls;
    arg1 = *(struct tuple **)&jarg1; 
    arg2 = (int)jarg2; 
    tuple_set_nil(arg1,arg2);
    
}


#ifdef __cplusplus
}
#endif

